#!/usr/bin/env ruby
#^syntax detection

forge "http://forge.puppetlabs.com"

mod 'SilexConsulting/beluga',
    :git => 'https://github.com/SilexConsulting/puppet-beluga.git'

mod 'SilexConsulting/apache',
    :git => 'https://github.com/SilexConsulting/puppetlabs-apache.git'

mod 'SilexConsulting/concat',
    :git => 'https://github.com/SilexConsulting/puppetlabs-concat.git'

mod 'SilexConsulting/ckan',
    :git => 'https://github.com/SilexConsulting/puppet_ckan.git'

mod 'SilexConsulting/elda',
    :git => 'https://github.com/SilexConsulting/puppet-elda.git'

mod 'SilexConsulting/firewall',
    :git => 'https://github.com/SilexConsulting/puppetlabs-firewall.git'

mod 'SilexConsulting/fuseki',
    :git => 'https://github.com/SilexConsulting/puppet-fuseki.git'

mod 'SilexConsulting/gitlab',
    :git => 'https://github.com/SilexConsulting/puppet-gitlab.git'

mod 'SilexConsulting/java',
    :git => 'https://github.com/SilexConsulting/puppetlabs-java.git'

mod 'SilexConsulting/jenkins',
    :git => 'https://github.com/SilexConsulting/puppet-jenkins.git'

mod 'SilexConsulting/mysql',
    :git => 'https://github.com/SilexConsulting/puppetlabs-mysql.git'

mod 'SilexConsulting/nginx',
    :git => 'https://github.com/SilexConsulting/puppet-nginx.git'

mod 'SilexConsulting/ntp',
   :git => 'https://github.com/puppetlabs/puppetlabs-ntp.git'

mod 'SilexConsulting/openldap',
    :git => 'https://github.com/SilexConsulting/puppetlabs-openldap.git'

mod 'SilexConsulting/orgdc',
    :git => 'https://github.com/SilexConsulting/puppet-orgdc.git'

mod 'SilexConsulting/stdlib',
    :git => 'https://github.com/SilexConsulting/puppetlabs-stdlib.git',
    :ref => '3.2.1'

mod 'SilexConsulting/postgresql',
    :git => 'https://github.com/SilexConsulting/puppetlabs-postgresql'

mod 'SilexConsulting/redis',
    :git => 'https://github.com/SilexConsulting/puppet-redis'

mod 'SilexConsulting/referencetimeserver',
    :git => 'https://github.com/SilexConsulting/puppet-referencetimeserver.git'

mod 'SilexConsulting/solr',
    :git => 'https://github.com/SilexConsulting/puppet-solr.git'

mod 'SilexConsulting/sudo',
    :git => 'https://github.com/SilexConsulting/puppet-sudo.git'

mod 'SilexConsulting/tomcat',
    :git => 'https://github.com/SilexConsulting/puppet-tomcat.git'

mod 'SilexConsulting/varnish',
    :git => 'https://github.com/SilexConsulting/puppet-varnish.git'

mod 'SilexConsulting/apt',
    :git => 'https://github.com/SilexConsulting/puppetlabs-apt'

mod 'SilexConsulting/memcached',
    :git => 'https://github.com/SilexConsulting/puppet-memcached'

mod 'SilexConsulting/nodejs',
    :git => 'https://github.com/SilexConsulting/puppet-nodejs.git'

mod 'SilexConsulting/composer',
    :git => 'https://github.com/SilexConsulting/puppet-composer.git'

mod 'SilexConsulting/wget',
    :git => 'https://github.com/SilexConsulting/puppet-wget.git'

mod 'SilexConsulting/postfix',
    :git => 'https://github.com/SilexConsulting/puppet-postfix.git'

mod 'datagovuk/dgu_solr',
    :git => 'https://github.com/datagovuk/dgu_solr.git'

mod 'SilexConsulting/rvm',
    :git => 'https://github.com/SilexConsulting/puppet-rvm.git'

mod 'SilexConsulting/python',
    :git => 'https://github.com/SilexConsulting/puppet-python.git'

mod 'SilexConsulting/uwsgi',
    :git => 'https://github.com/SilexConsulting/puppet-uwsgi.git'
