#!/usr/bin/env ruby
#^syntax detection

forge "http://forge.puppetlabs.com"

mod 'beluga',
    :git => 'https://github.com/SilexConsulting/puppet-beluga.git'

mod 'apache',
    :git => 'https://github.com/SilexConsulting/puppetlabs-apache.git'

mod 'concat',
    :git => 'https://github.com/SilexConsulting/puppetlabs-concat.git'

mod 'puppetlabs/firewall',
    :git => 'https://github.com/SilexConsulting/puppetlabs-firewall.git'

mod 'gitlab',
    :git => 'https://github.com/SilexConsulting/puppet-gitlab.git'

mod 'java',
    :git => 'https://github.com/SilexConsulting/puppetlabs-java.git'

mod 'jenkins',
    :git => 'https://github.com/SilexConsulting/puppet-jenkins.git'

mod 'mysql',
    :git => 'https://github.com/SilexConsulting/puppetlabs-mysql.git'

mod 'nginx',
    :git => 'https://github.com/SilexConsulting/puppet-nginx.git'

mod 'ntp',
   :git => 'https://github.com/puppetlabs/puppetlabs-ntp.git'

mod 'openldap',
    :git => 'https://github.com/SilexConsulting/puppetlabs-openldap.git'

mod 'stdlib',
    :git => 'https://github.com/SilexConsulting/puppetlabs-stdlib.git',
    :ref => '3.2.1'

mod 'postgresql',
    :git => 'https://github.com/SilexConsulting/puppetlabs-postgresql'

mod 'solr',
    :git => 'https://github.com/SilexConsulting/puppet-solr.git'

mod 'tomcat',
    :git => 'https://github.com/SilexConsulting/puppet-tomcat.git'

mod 'varnish',
    :git => 'https://github.com/SilexConsulting/puppet-varnish.git'

mod 'apt',
    :git => 'https://github.com/SilexConsulting/puppetlabs-apt'

mod 'memcached',
    :git => 'https://github.com/SilexConsulting/puppet-memcached'

mod 'nodejs',
    :git => 'https://github.com/SilexConsulting/puppet-nodejs.git'

mod 'composer',
    :git => 'https://github.com/SilexConsulting/puppet-composer.git'

mod 'wget',
    :git => 'https://github.com/SilexConsulting/puppet-wget.git'

mod 'postfix',
    :git => 'https://github.com/SilexConsulting/puppet-postfix.git'
